### ISSUE TITLE
Inclusion/Exclusion refinement - 1

### ISSUE THREAD

**Issue by parthopdas** [digitalpalitools/pure-machine-readable-corpus#3]
from v @bdhrs 
- Exclude \<p rend="subsubhead"\> 
There are a few headings included because they have “bodytext” tag but i’m not sure if it is worth the trouble of isolating these individually. Perhaps a doc somewhere where we keep track of glitches in VRI CST

- I’m in occasional doubt about the “centre” tag because occasionally there is useful information in there, but still, it's not part of the actual text.

- Please delete this exclusion rule, “any line in any book that includes the word paṇṇāsakaṃ should be excluded, eg "catutthapaṇṇāsakaṃ samattaṃ". i will refer to html tags in future, not their text contents.
 
- In included, there are spaces at the beginning and many double spaces leftover by deletions

**Comment by bdhrs** [comment]
compiled into #5
