### ISSUE TITLE
Inclusion/Exclusion refinement - 2

### ISSUE THREAD

**Issue by parthopdas** [digitalpalitools/pure-machine-readable-corpus#4]
- When there is a page number, there is no space between two words. Test with yopana

- Still some numbers in text, especially in the middle of text eg https://d.pali.tools/apps#/word-frequency/e0802n.nrf2.xml

- Square bracket [ ] in https://d.pali.tools/apps#/word-frequency/vin02m2.mul0.xml
And https://d.pali.tools/apps#/word-frequency/e0201n.nrf2.xml etc, but see the next one, i think that is more applicable

- Here square brackets and everything in them can be excluded https://d.pali.tools/apps#/word-frequency/s0516m.mul0.xml same here https://d.pali.tools/apps#/word-frequency/s0516m.mul1.xml

- Equals sign = in https://d.pali.tools/apps#/word-frequency/e0802n.nrf6.xml

- Colon : in https://d.pali.tools/apps#/word-frequency/s0203m.mul0.xml

- Open bracket ( ) in https://d.pali.tools/apps#/word-frequency/e0807n.nrf0.xml
And https://d.pali.tools/apps#/word-frequency/vin02m3.mul4.xml

- There are a few devanagiri characters in https://d.pali.tools/apps#/word-frequency/e1201n.nrf.xml i don’t know those books, so i’m not sure if they should be transliterated into roman. 

- The plus + must be included as it is used in grammar books

- Exclude this kind of pali “numbering” [k] [kha] [g] [gh] [ṅa] [c] [ch] [j] [jh] [ñ] = 1 2 3 4 5 6 7 8 9 10  https://d.pali.tools/apps#/word-frequency/e0301n.nrf0.xml

**Comment by bdhrs** [comment]
compiled into #3

**Comment by bdhrs** [comment]
compiled into #5
